import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/layout/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="bg-gray-100">
          <div className="min-h-screen">
            <Header />
            <div className="border-b border-gray-300/90" />
            <main className="min-h-[94vh] max-w-container mx-auto">
              {children}
            </main>
          </div>
        </section>
      </body>
    </html>
  );
}
